//! Explicit adapter for Pocket's embedded SQLite light-client profile.
//!
//! This module is intentionally separate from the pinned upstream adapter.
//! Pocket stores the same ckb-light-client logical key/value families in a
//! table named `kv`, rather than the pinned upstream `kv_store` table.  The
//! adapter accepts only that profile and does not import Pocket Room data,
//! wallet keys, or any global chain-authority rows from the artifact.

use std::{
    collections::BTreeSet,
    fs::{File, OpenOptions},
    ops::Deref,
    path::{Path, PathBuf},
    sync::{Arc, Mutex},
};

use ckb_light_client_lib::storage::{Key, KeyPrefix};
use ckb_types::{packed, prelude::*};
use fs2::FileExt;
use rusqlite::{params, Connection, OptionalExtension};

use crate::{
    Artifact, D2Error, DestinationAuthority, ImportResult, ResourceLimits, Result, Row, ScriptRole,
    StorageAdapter,
};

/// The only Pocket profile accepted by this adapter.
pub const POCKET_PROFILE: &str =
    "pocket-node@6eda0b7a4601050b011591d41cc702f0dc7a7c38/ckb-light-client@0.5.4/kv-v1";

const LAST_STATE_KEY: &str = "LAST_STATE";
const LAST_N_HEADERS_KEY: &str = "LAST_N_HEADERS";
const GENESIS_BLOCK_KEY: &str = "GENESIS_BLOCK";
const FILTER_SCRIPTS_KEY: &str = "FILTER_SCRIPTS";
const MIN_FILTERED_NUMBER_KEY: &str = "MIN_FILTERED_NUMBER";

struct ExclusiveGuard {
    file: Option<File>,
}

impl Drop for ExclusiveGuard {
    fn drop(&mut self) {
        if let Some(file) = self.file.as_ref() {
            let _ = file.unlock();
        }
    }
}

/// Adapter for the native SQLite file generated by Pocket's embedded light
/// client.  Callers must stop Pocket's JNI/client workers before opening this
/// adapter for a mutation; the lock file prevents competing D2 operations but
/// cannot identify an unrelated Android process that ignores the D2 lock.
pub struct PocketSqliteAdapter {
    conn: Arc<Mutex<Connection>>,
    path: PathBuf,
    preopened_exclusive: Arc<Mutex<Option<File>>>,
}

impl PocketSqliteAdapter {
    /// Opens and profile-checks a Pocket `store.db`.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        Self::open_inner(path.as_ref(), None)
    }

    /// Acquires D2's process-safe exclusive lifecycle lock before opening a
    /// Pocket database.  This is the constructor required for import.
    pub fn open_exclusive(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref().to_path_buf();
        let lock_path = lifecycle_lock_path(&path);
        let file = open_lock_file(&lock_path)?;
        file.try_lock_exclusive().map_err(|error| {
            D2Error::Lifecycle(format!(
                "Pocket destination is not exclusively offline: {error}"
            ))
        })?;
        Self::open_inner(&path, Some(file))
    }

    /// Returns the Pocket database path used for diagnostics.
    pub fn path(&self) -> &Path {
        &self.path
    }

    fn open_inner(path: &Path, lock: Option<File>) -> Result<Self> {
        let conn = Connection::open(path)
            .map_err(|error| D2Error::Storage(format!("open Pocket SQLite failed: {error}")))?;
        validate_pocket_schema(&conn)?;
        Ok(Self {
            conn: Arc::new(Mutex::new(conn)),
            path: path.to_path_buf(),
            preopened_exclusive: Arc::new(Mutex::new(lock)),
        })
    }

    fn acquire_exclusive(&self) -> Result<ExclusiveGuard> {
        if self
            .preopened_exclusive
            .lock()
            .map_err(|_| D2Error::Lifecycle("Pocket lifecycle mutex poisoned".into()))?
            .is_some()
        {
            return Ok(ExclusiveGuard { file: None });
        }
        let file = open_lock_file(&lifecycle_lock_path(&self.path))?;
        file.try_lock_exclusive().map_err(|error| {
            D2Error::Lifecycle(format!(
                "Pocket destination is not exclusively offline: {error}"
            ))
        })?;
        Ok(ExclusiveGuard { file: Some(file) })
    }

    fn read(&self, key: &[u8]) -> Result<Option<Vec<u8>>> {
        let conn = self
            .conn
            .lock()
            .map_err(|_| D2Error::Storage("Pocket SQLite mutex poisoned".into()))?;
        read_value(&conn, key)
    }

    fn statuses(&self) -> Result<Vec<Status>> {
        let conn = self
            .conn
            .lock()
            .map_err(|_| D2Error::Storage("Pocket SQLite mutex poisoned".into()))?;
        collect_statuses(&conn)
    }

    fn validate_destination_unlocked(
        &self,
        artifact: &Artifact,
        limits: &ResourceLimits,
    ) -> Result<bool> {
        validate_pocket_artifact(artifact, limits)?;
        let existing = exact_status(self, &artifact.script, artifact.role)?;
        if existing.is_some_and(|cursor| cursor > artifact.cursor) {
            return Err(D2Error::StaleState(format!(
                "Pocket destination cursor exceeds artifact cursor {}",
                artifact.cursor
            )));
        }
        let all_rows_present = check_existing_rows(self, artifact)?;
        Ok(existing == Some(artifact.cursor) && all_rows_present)
    }
}

impl StorageAdapter for PocketSqliteAdapter {
    fn adapter_profile(&self) -> &str {
        POCKET_PROFILE
    }

    fn export(
        &self,
        script_bytes: &[u8],
        role: ScriptRole,
        limits: &ResourceLimits,
    ) -> Result<Artifact> {
        let _exclusive = self.acquire_exclusive()?;
        let script = packed::Script::from_slice(script_bytes).map_err(|error| {
            D2Error::IdentityMismatch(format!("Pocket packed Script decode failed: {error:?}"))
        })?;
        let script_type = role_byte(role);
        let status = self
            .statuses()?
            .into_iter()
            .find(|status| status.script == script_bytes && status.role == script_type)
            .ok_or_else(|| {
                D2Error::IdentityMismatch("exact Pocket Script+role is not registered".into())
            })?;
        let genesis_hash = read_genesis_hash(self)?;
        let handoff_hash = read_block_hash(self, status.cursor)?;
        let (index_rows, transaction_index_rows, transaction_rows) =
            collect_rows(self, &script, role, limits)?;
        let artifact = Artifact {
            format_version: crate::FORMAT_VERSION,
            adapter_profile: POCKET_PROFILE.to_owned(),
            genesis_hash,
            script: script_bytes.to_vec(),
            role,
            handoff_height: status.cursor,
            handoff_hash,
            cursor: status.cursor,
            index_rows,
            transaction_index_rows,
            transaction_rows,
        };
        artifact.validate(limits)?;
        Ok(artifact)
    }

    fn destination_authority(&self, handoff_height: u64) -> Result<DestinationAuthority> {
        Ok(DestinationAuthority {
            genesis_hash: read_genesis_hash(self)?,
            handoff_hash: read_block_hash(self, handoff_height)?,
            tip_height: read_tip_height(self)?,
        })
    }

    fn validate_destination(&self, artifact: &Artifact, limits: &ResourceLimits) -> Result<bool> {
        let _exclusive = self.acquire_exclusive()?;
        self.validate_destination_unlocked(artifact, limits)
    }

    fn import_atomically(
        &self,
        artifact: &Artifact,
        limits: &ResourceLimits,
    ) -> Result<ImportResult> {
        let _exclusive = self.acquire_exclusive()?;
        validate_pocket_artifact(artifact, limits)?;
        validate_pocket_authority(self, artifact)?;
        let already_present = self.validate_destination_unlocked(artifact, limits)?;

        let mut conn = self
            .conn
            .lock()
            .map_err(|_| D2Error::Storage("Pocket SQLite mutex poisoned".into()))?;
        let tx = conn.transaction().map_err(|error| {
            D2Error::Storage(format!("begin Pocket transaction failed: {error}"))
        })?;

        for row in artifact
            .index_rows
            .iter()
            .chain(artifact.transaction_index_rows.iter())
            .chain(artifact.transaction_rows.iter())
        {
            match read_value(&tx, &row.key)? {
                Some(existing) if existing != row.value => {
                    return Err(D2Error::DestinationConflict(
                        "existing Pocket row value differs from artifact".into(),
                    ));
                }
                Some(_) => {}
                None => {
                    tx.execute(
                        "INSERT INTO kv (key, value) VALUES (?1, ?2)",
                        params![&row.key, &row.value],
                    )
                    .map_err(|error| {
                        D2Error::Storage(format!("insert Pocket handoff row failed: {error}"))
                    })?;
                }
            }
        }

        let status_key = filter_script_key(&artifact.script, artifact.role)?;
        tx.execute(
            "INSERT INTO kv (key, value) VALUES (?1, ?2)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            params![status_key, artifact.cursor.to_be_bytes().as_slice()],
        )
        .map_err(|error| D2Error::Storage(format!("write Pocket Script cursor failed: {error}")))?;

        let min = collect_statuses_tx(&tx)?
            .into_iter()
            .map(|status| status.cursor)
            .min()
            .ok_or_else(|| D2Error::Invariant("imported Pocket cursor disappeared".into()))?;
        let min_key = Key::Meta(MIN_FILTERED_NUMBER_KEY).into_vec();
        tx.execute(
            "INSERT INTO kv (key, value) VALUES (?1, ?2)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            params![min_key, min.to_le_bytes().as_slice()],
        )
        .map_err(|error| {
            D2Error::Storage(format!("write Pocket minimum cursor failed: {error}"))
        })?;
        tx.commit()
            .map_err(|error| D2Error::Storage(format!("commit Pocket handoff failed: {error}")))?;
        drop(conn);

        verify_imported_state(self, artifact)?;
        Ok(ImportResult {
            script: artifact.script.clone(),
            role: artifact.role,
            handoff_height: artifact.handoff_height,
            handoff_hash: artifact.handoff_hash,
            digest: artifact.digest(limits)?,
            index_rows: artifact.index_rows.len(),
            transaction_index_rows: artifact.transaction_index_rows.len(),
            transaction_rows: artifact.transaction_rows.len(),
            idempotent: already_present,
        })
    }
}

#[derive(Debug)]
struct Status {
    script: Vec<u8>,
    role: u8,
    cursor: u64,
}

fn validate_pocket_schema(conn: &Connection) -> Result<()> {
    let table: Option<String> = conn
        .query_row(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'kv'",
            [],
            |row| row.get(0),
        )
        .optional()
        .map_err(|error| D2Error::Storage(format!("inspect Pocket schema failed: {error}")))?;
    if table.is_none() {
        return Err(D2Error::UnsupportedProfile(
            "Pocket database has no kv table".into(),
        ));
    }

    let mut stmt = conn
        .prepare("PRAGMA table_info(kv)")
        .map_err(|error| D2Error::Storage(format!("inspect Pocket kv schema failed: {error}")))?;
    let mut rows = stmt
        .query([])
        .map_err(|error| D2Error::Storage(format!("read Pocket kv schema failed: {error}")))?;
    let mut key_ok = false;
    let mut value_ok = false;
    while let Some(row) = rows
        .next()
        .map_err(|error| D2Error::Storage(format!("iterate Pocket kv schema failed: {error}")))?
    {
        let name: String = row.get(1).map_err(sqlite_error)?;
        let data_type: String = row.get(2).map_err(sqlite_error)?;
        let primary_key: i64 = row.get(5).map_err(sqlite_error)?;
        if name == "key" && data_type.eq_ignore_ascii_case("BLOB") && primary_key == 1 {
            key_ok = true;
        }
        if name == "value" && data_type.eq_ignore_ascii_case("BLOB") {
            value_ok = true;
        }
    }
    if !key_ok || !value_ok {
        return Err(D2Error::UnsupportedProfile(
            "Pocket kv schema is not key BLOB PRIMARY KEY/value BLOB".into(),
        ));
    }
    let nulls: i64 = conn
        .query_row(
            "SELECT count(*) FROM kv WHERE key IS NULL OR value IS NULL",
            [],
            |row| row.get(0),
        )
        .map_err(|error| D2Error::Storage(format!("inspect Pocket kv nulls failed: {error}")))?;
    if nulls != 0 {
        return Err(D2Error::Invariant(
            "Pocket kv contains a null key or value".into(),
        ));
    }
    Ok(())
}

fn sqlite_error(error: rusqlite::Error) -> D2Error {
    D2Error::Storage(format!("Pocket SQLite row read failed: {error}"))
}

fn lifecycle_lock_path(path: &Path) -> PathBuf {
    path.with_extension("d2.lock")
}

fn open_lock_file(path: &Path) -> Result<File> {
    OpenOptions::new()
        .create(true)
        .truncate(false)
        .read(true)
        .write(true)
        .open(path)
        .map_err(|error| D2Error::Lifecycle(format!("open Pocket lifecycle lock failed: {error}")))
}

fn read_value<C>(conn: &C, key: &[u8]) -> Result<Option<Vec<u8>>>
where
    C: Deref<Target = Connection>,
{
    conn.deref()
        .query_row("SELECT value FROM kv WHERE key = ?1", params![key], |row| {
            row.get(0)
        })
        .optional()
        .map_err(|error| D2Error::Storage(format!("read Pocket kv row failed: {error}")))
}

fn status_prefix() -> Vec<u8> {
    Key::Meta(FILTER_SCRIPTS_KEY).into_vec()
}

fn collect_statuses<C>(conn: &C) -> Result<Vec<Status>>
where
    C: Deref<Target = Connection>,
{
    collect_statuses_impl(conn)
}

fn collect_statuses_tx(conn: &rusqlite::Transaction<'_>) -> Result<Vec<Status>> {
    collect_statuses_impl(conn)
}

fn collect_statuses_impl<C>(conn: &C) -> Result<Vec<Status>>
where
    C: Deref<Target = Connection>,
{
    let prefix = status_prefix();
    let upper = exclusive_upper_bound(&prefix);
    let mut stmt = conn
        .deref()
        .prepare("SELECT key, value FROM kv WHERE key >= ?1 AND key < ?2 ORDER BY key")
        .map_err(|error| {
            D2Error::Storage(format!("prepare Pocket status query failed: {error}"))
        })?;
    let mut rows = stmt
        .query(params![&prefix, &upper])
        .map_err(|error| D2Error::Storage(format!("query Pocket Script status failed: {error}")))?;
    let mut statuses = Vec::new();
    while let Some(row) = rows.next().map_err(sqlite_error)? {
        let key: Vec<u8> = row.get(0).map_err(sqlite_error)?;
        let value: Vec<u8> = row.get(1).map_err(sqlite_error)?;
        if key.len() <= prefix.len() + 1 || value.len() != 8 {
            return Err(D2Error::Invariant(
                "Pocket FILTER_SCRIPTS row has invalid shape".into(),
            ));
        }
        let script =
            packed::Script::from_slice(&key[prefix.len()..key.len() - 1]).map_err(|error| {
                D2Error::Invariant(format!("Pocket stored Script is invalid: {error:?}"))
            })?;
        let role = *key.last().unwrap();
        if role > 1 {
            return Err(D2Error::Invariant(
                "Pocket FILTER_SCRIPTS role byte is invalid".into(),
            ));
        }
        statuses.push(Status {
            script: script.as_slice().to_vec(),
            role,
            cursor: u64::from_be_bytes(value.try_into().unwrap()),
        });
    }
    Ok(statuses)
}

fn exact_status(
    adapter: &PocketSqliteAdapter,
    script: &[u8],
    role: ScriptRole,
) -> Result<Option<u64>> {
    let key = filter_script_key(script, role)?;
    let Some(value) = adapter.read(&key)? else {
        return Ok(None);
    };
    if value.len() != 8 {
        return Err(D2Error::Invariant(
            "Pocket exact Script cursor has invalid length".into(),
        ));
    }
    Ok(Some(u64::from_be_bytes(value.try_into().unwrap())))
}

fn filter_script_key(script: &[u8], role: ScriptRole) -> Result<Vec<u8>> {
    packed::Script::from_slice(script).map_err(|error| {
        D2Error::IdentityMismatch(format!("Pocket packed Script decode failed: {error:?}"))
    })?;
    let mut key = status_prefix();
    key.extend_from_slice(script);
    key.push(role_byte(role));
    Ok(key)
}

fn role_byte(role: ScriptRole) -> u8 {
    match role {
        ScriptRole::Lock => 0,
        ScriptRole::Type => 1,
    }
}

fn raw_script_prefix(script: &packed::Script, prefix: KeyPrefix) -> Vec<u8> {
    let mut key = vec![prefix as u8];
    key.extend_from_slice(&ckb_light_client_lib::storage::extract_raw_data(script));
    key
}

fn collect_rows(
    adapter: &PocketSqliteAdapter,
    script: &packed::Script,
    role: ScriptRole,
    limits: &ResourceLimits,
) -> Result<(Vec<Row>, Vec<Row>, Vec<Row>)> {
    let (cell_prefix, tx_prefix) = match role {
        ScriptRole::Lock => (
            raw_script_prefix(script, KeyPrefix::CellLockScript),
            raw_script_prefix(script, KeyPrefix::TxLockScript),
        ),
        ScriptRole::Type => (
            raw_script_prefix(script, KeyPrefix::CellTypeScript),
            raw_script_prefix(script, KeyPrefix::TxTypeScript),
        ),
    };
    let index_rows = collect_prefix(adapter, &cell_prefix, limits.max_rows_per_section)?;
    let transaction_index_rows = collect_prefix(adapter, &tx_prefix, limits.max_rows_per_section)?;
    validate_index_rows(&index_rows, &cell_prefix, 16)?;
    validate_index_rows(&transaction_index_rows, &tx_prefix, 17)?;

    let hashes = index_rows
        .iter()
        .chain(transaction_index_rows.iter())
        .map(|row| {
            if row.value.len() != 32 {
                return Err(D2Error::ClosureFailure(
                    "Pocket Script index value is not a transaction hash".into(),
                ));
            }
            let mut hash = [0u8; 32];
            hash.copy_from_slice(&row.value);
            Ok(hash)
        })
        .collect::<Result<BTreeSet<_>>>()?;
    if hashes.len() > limits.max_transaction_rows {
        return Err(D2Error::ResourceLimit(format!(
            "Pocket transaction closure exceeds limit {}",
            limits.max_transaction_rows
        )));
    }
    let mut transaction_rows = Vec::with_capacity(hashes.len());
    for hash in hashes {
        let tx_hash = packed::Byte32::from_slice(&hash).map_err(|error| {
            D2Error::ClosureFailure(format!("Pocket transaction hash decode failed: {error:?}"))
        })?;
        let key = Key::TxHash(&tx_hash).into_vec();
        let value = adapter.read(&key)?.ok_or_else(|| {
            D2Error::ClosureFailure("Pocket referenced transaction is missing".into())
        })?;
        validate_transaction_value(&key, &value)?;
        transaction_rows.push(Row { key, value });
    }
    transaction_rows.sort_by(|left, right| left.key.cmp(&right.key));
    Ok((index_rows, transaction_index_rows, transaction_rows))
}

fn collect_prefix(adapter: &PocketSqliteAdapter, prefix: &[u8], limit: usize) -> Result<Vec<Row>> {
    let upper = exclusive_upper_bound(prefix);
    let conn = adapter
        .conn
        .lock()
        .map_err(|_| D2Error::Storage("Pocket SQLite mutex poisoned".into()))?;
    let mut stmt = conn
        .prepare("SELECT key, value FROM kv WHERE key >= ?1 AND key < ?2 ORDER BY key LIMIT ?3")
        .map_err(|error| {
            D2Error::Storage(format!("prepare Pocket prefix query failed: {error}"))
        })?;
    let mut rows = stmt
        .query(params![prefix, &upper, (limit.saturating_add(1)) as i64])
        .map_err(|error| D2Error::Storage(format!("query Pocket Script rows failed: {error}")))?;
    let mut output = Vec::new();
    while let Some(row) = rows.next().map_err(sqlite_error)? {
        output.push(Row {
            key: row.get(0).map_err(sqlite_error)?,
            value: row.get(1).map_err(sqlite_error)?,
        });
    }
    if output.len() > limit {
        return Err(D2Error::ResourceLimit(format!(
            "Pocket Script index rows exceed limit {limit}"
        )));
    }
    Ok(output)
}

fn validate_index_rows(rows: &[Row], prefix: &[u8], suffix_len: usize) -> Result<()> {
    for row in rows {
        if row.key.len() != prefix.len() + suffix_len || !row.key.starts_with(prefix) {
            return Err(D2Error::Invariant(
                "Pocket Script index key has unexpected shape".into(),
            ));
        }
        if row.value.len() != 32 {
            return Err(D2Error::ClosureFailure(
                "Pocket Script index value has unexpected shape".into(),
            ));
        }
    }
    Ok(())
}

fn validate_transaction_value(key: &[u8], value: &[u8]) -> Result<()> {
    if key.len() != 33 || key[0] != KeyPrefix::TxHash as u8 || value.len() < 12 {
        return Err(D2Error::ClosureFailure(
            "Pocket transaction row has unexpected shape".into(),
        ));
    }
    let transaction = packed::Transaction::from_slice(&value[12..]).map_err(|error| {
        D2Error::ClosureFailure(format!("Pocket transaction decode failed: {error:?}"))
    })?;
    if transaction.calc_tx_hash().as_slice() != &key[1..] {
        return Err(D2Error::ClosureFailure(
            "Pocket transaction key does not match transaction value".into(),
        ));
    }
    Ok(())
}

fn validate_pocket_artifact(artifact: &Artifact, limits: &ResourceLimits) -> Result<()> {
    if artifact.adapter_profile != POCKET_PROFILE {
        return Err(D2Error::UnsupportedProfile(
            artifact.adapter_profile.clone(),
        ));
    }
    artifact.validate(limits)?;
    let script = packed::Script::from_slice(&artifact.script).map_err(|error| {
        D2Error::IdentityMismatch(format!("Pocket packed Script decode failed: {error:?}"))
    })?;
    let (cell, tx) = match artifact.role {
        ScriptRole::Lock => (
            raw_script_prefix(&script, KeyPrefix::CellLockScript),
            raw_script_prefix(&script, KeyPrefix::TxLockScript),
        ),
        ScriptRole::Type => (
            raw_script_prefix(&script, KeyPrefix::CellTypeScript),
            raw_script_prefix(&script, KeyPrefix::TxTypeScript),
        ),
    };
    validate_index_rows(&artifact.index_rows, &cell, 16)?;
    validate_index_rows(&artifact.transaction_index_rows, &tx, 17)?;
    for row in &artifact.transaction_rows {
        validate_transaction_value(&row.key, &row.value)?;
    }
    for row in artifact
        .index_rows
        .iter()
        .chain(artifact.transaction_index_rows.iter())
        .chain(artifact.transaction_rows.iter())
    {
        if row.key.first().copied().unwrap_or_default() >= KeyPrefix::BlockHash as u8 {
            return Err(D2Error::IdentityMismatch(
                "Pocket artifact contains a forbidden authority/global row".into(),
            ));
        }
    }
    Ok(())
}

fn check_existing_rows(adapter: &PocketSqliteAdapter, artifact: &Artifact) -> Result<bool> {
    let mut all_present = true;
    for row in artifact
        .index_rows
        .iter()
        .chain(artifact.transaction_index_rows.iter())
        .chain(artifact.transaction_rows.iter())
    {
        match adapter.read(&row.key)? {
            Some(existing) if existing != row.value => {
                return Err(D2Error::DestinationConflict(
                    "existing Pocket row value differs from artifact".into(),
                ));
            }
            Some(_) => {}
            None => all_present = false,
        }
    }
    Ok(all_present)
}

fn read_genesis_hash(adapter: &PocketSqliteAdapter) -> Result<[u8; 32]> {
    let value = adapter
        .read(&Key::Meta(GENESIS_BLOCK_KEY).into_vec())?
        .ok_or_else(|| D2Error::Storage("Pocket genesis is not initialized".into()))?;
    if value.len() < 32 {
        return Err(D2Error::Storage(
            "Pocket genesis metadata is truncated".into(),
        ));
    }
    Ok(value[..32].try_into().unwrap())
}

fn read_block_hash(adapter: &PocketSqliteAdapter, height: u64) -> Result<[u8; 32]> {
    if let Some(value) = adapter.read(&Key::BlockNumber(height).into_vec())? {
        if value.len() != 32 {
            return Err(D2Error::HandoffMismatch(
                "Pocket block-number value has invalid length".into(),
            ));
        }
        return Ok(value.try_into().unwrap());
    }
    if let Some(value) = adapter.read(&Key::Meta(LAST_N_HEADERS_KEY).into_vec())? {
        if value.len() % 40 != 0 {
            return Err(D2Error::HandoffMismatch(
                "Pocket LAST_N_HEADERS has invalid length".into(),
            ));
        }
        for header in value.chunks_exact(40) {
            let number = u64::from_le_bytes(header[..8].try_into().unwrap());
            if number == height {
                return Ok(header[8..].try_into().unwrap());
            }
        }
    }
    let value = adapter
        .read(&Key::Meta(LAST_STATE_KEY).into_vec())?
        .ok_or_else(|| {
            D2Error::HandoffMismatch(format!("Pocket has no block hash at height {height}"))
        })?;
    if value.len() < 32 + packed::Header::TOTAL_SIZE {
        return Err(D2Error::HandoffMismatch(
            "Pocket LAST_STATE is truncated".into(),
        ));
    }
    let header = packed::Header::from_slice(&value[32..]).map_err(|error| {
        D2Error::HandoffMismatch(format!("Pocket LAST_STATE header is invalid: {error:?}"))
    })?;
    let header_height: u64 = header.raw().number().unpack();
    if header_height != height {
        return Err(D2Error::HandoffMismatch(format!(
            "Pocket has no block hash at height {height}"
        )));
    }
    Ok(header.calc_header_hash().as_slice().try_into().unwrap())
}

fn read_tip_height(adapter: &PocketSqliteAdapter) -> Result<u64> {
    let value = adapter
        .read(&Key::Meta(LAST_STATE_KEY).into_vec())?
        .ok_or_else(|| D2Error::Storage("Pocket LAST_STATE is not initialized".into()))?;
    if value.len() < 32 + packed::Header::TOTAL_SIZE {
        return Err(D2Error::Storage("Pocket LAST_STATE is truncated".into()));
    }
    let header = packed::Header::from_slice(&value[32..]).map_err(|error| {
        D2Error::Storage(format!("Pocket LAST_STATE header is invalid: {error:?}"))
    })?;
    Ok(header.raw().number().unpack())
}

fn validate_pocket_authority(adapter: &PocketSqliteAdapter, artifact: &Artifact) -> Result<()> {
    if read_genesis_hash(adapter)? != artifact.genesis_hash {
        return Err(D2Error::ChainGenesisMismatch(
            "Pocket destination genesis differs from artifact".into(),
        ));
    }
    if read_block_hash(adapter, artifact.handoff_height)? != artifact.handoff_hash {
        return Err(D2Error::HandoffMismatch(
            "Pocket destination handoff hash differs from artifact".into(),
        ));
    }
    if artifact.handoff_height > read_tip_height(adapter)? {
        return Err(D2Error::HandoffMismatch(
            "Pocket destination tip is below artifact handoff".into(),
        ));
    }
    Ok(())
}

fn verify_imported_state(adapter: &PocketSqliteAdapter, artifact: &Artifact) -> Result<()> {
    for row in artifact
        .index_rows
        .iter()
        .chain(artifact.transaction_index_rows.iter())
        .chain(artifact.transaction_rows.iter())
    {
        if adapter.read(&row.key)?.as_deref() != Some(row.value.as_slice()) {
            return Err(D2Error::Storage(
                "Pocket committed row failed post-commit verification".into(),
            ));
        }
    }
    if exact_status(adapter, &artifact.script, artifact.role)? != Some(artifact.cursor) {
        return Err(D2Error::Storage(
            "Pocket committed Script cursor failed post-commit verification".into(),
        ));
    }
    Ok(())
}

fn exclusive_upper_bound(prefix: &[u8]) -> Vec<u8> {
    let mut upper = prefix.to_vec();
    for index in (0..upper.len()).rev() {
        if upper[index] != u8::MAX {
            upper[index] += 1;
            upper.truncate(index + 1);
            return upper;
        }
    }
    upper.push(0);
    upper
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    fn required(name: &str) -> String {
        std::env::var(name).unwrap_or_else(|_| panic!("missing {name}"))
    }

    fn hex_decode(input: &str) -> Vec<u8> {
        (0..input.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&input[i..i + 2], 16).unwrap())
            .collect()
    }

    fn hex_encode(input: &[u8]) -> String {
        input.iter().map(|byte| format!("{byte:02x}")).collect()
    }

    /// Executes the production Pocket adapter against a genuine captured
    /// Pocket store. The destination is a disposable authority-preserving
    /// SQLite copy with only the selected Script registration removed.
    #[test]
    #[ignore = "requires D2_POCKET_SOURCE and D2_POCKET_DEST"]
    fn production_pocket_export_validate_import() {
        let source_path = PathBuf::from(required("D2_POCKET_SOURCE"));
        let destination_path = PathBuf::from(required("D2_POCKET_DEST"));
        let script = hex_decode(&required("D2_POCKET_SCRIPT"));
        fs::copy(&source_path, &destination_path).unwrap();
        for suffix in ["-wal", "-shm"] {
            let source_sidecar = PathBuf::from(format!("{}{}", source_path.display(), suffix));
            let destination_sidecar =
                PathBuf::from(format!("{}{}", destination_path.display(), suffix));
            if source_sidecar.exists() {
                fs::copy(source_sidecar, destination_sidecar).unwrap();
            }
        }
        let conn = Connection::open(&destination_path).unwrap();
        let key = filter_script_key(&script, ScriptRole::Lock).unwrap();
        conn.execute("DELETE FROM kv WHERE key = ?1", params![key])
            .unwrap();
        let packed_script = packed::Script::from_slice(&script).unwrap();
        for prefix in [
            raw_script_prefix(&packed_script, KeyPrefix::CellLockScript),
            raw_script_prefix(&packed_script, KeyPrefix::TxLockScript),
        ] {
            let upper = exclusive_upper_bound(&prefix);
            conn.execute(
                "DELETE FROM kv WHERE key >= ?1 AND key < ?2",
                params![prefix, upper],
            )
            .unwrap();
        }
        drop(conn);

        let source = PocketSqliteAdapter::open(&source_path).unwrap();
        eprintln!("pocket-source tip={}", read_tip_height(&source).unwrap());
        let exported = crate::D2::new(source)
            .export(&script, ScriptRole::Lock)
            .unwrap();
        assert_eq!(exported.artifact.adapter_profile, POCKET_PROFILE);
        assert!(!exported.artifact.index_rows.is_empty());
        assert!(!exported.artifact.transaction_index_rows.is_empty());
        assert!(!exported.artifact.transaction_rows.is_empty());
        eprintln!(
            "pocket-export profile={} handoff_height={} handoff_hash=0x{} index_rows={} transaction_index_rows={} transaction_rows={} artifact_bytes={}",
            exported.artifact.adapter_profile,
            exported.artifact.handoff_height,
            hex_encode(&exported.artifact.handoff_hash),
            exported.artifact.index_rows.len(),
            exported.artifact.transaction_index_rows.len(),
            exported.artifact.transaction_rows.len(),
            exported.bytes.len(),
        );
        if let Ok(path) = std::env::var("D2_POCKET_ARTIFACT") {
            fs::write(path, &exported.bytes).unwrap();
        }

        let destination = PocketSqliteAdapter::open_exclusive(&destination_path).unwrap();
        let d2 = crate::D2::new(destination);
        let inspection = d2.inspect(&exported.bytes).unwrap();
        assert_eq!(inspection.script, script);
        assert_eq!(inspection.role, ScriptRole::Lock);
        assert!(!d2.validate(&exported.bytes).unwrap().idempotent);
        let result = d2.import(&exported.bytes).unwrap();
        assert!(!result.idempotent);
        assert_eq!(result.handoff_height, exported.artifact.handoff_height);

        drop(d2);
        let reopened = crate::D2::new(PocketSqliteAdapter::open(&destination_path).unwrap());
        assert!(reopened.validate(&exported.bytes).unwrap().idempotent);
        assert!(reopened.import(&exported.bytes).unwrap().idempotent);
    }
}
